FROM node:18-alpine

RUN mkdir -p /opt/ignitegyn


WORKDIR /opt/ignitegyn

COPY package*.json ./
COPY turbo.json ./
COPY apps/backend  ./apps/backend

RUN npm install

EXPOSE 3333

CMD ["npm", "run", "start:server"]
